---
# cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: one
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello, World!"
          restartPolicy: OnFailure
---
# cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: two
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello, World!"; exit 1
          restartPolicy: Never
