# This file was generated by GoReleaser. DO NOT EDIT.
class KubernetesJobUi < Formula
  desc ""
  homepage ""
  version "0.1.0"

  if OS.mac?
    url "https://github.com/lhopki01/kubernetes-job-ui/releases/download/v0.1.0/kubernetes-job-ui_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "5aed261006dff54a28d4f0a201cef15b9f0f826c6bdfdd8ddc36eb7a56480009"
  elsif OS.linux?
    url "https://github.com/lhopki01/kubernetes-job-ui/releases/download/v0.1.0/kubernetes-job-ui_0.1.0_Linux_x86_64.tar.gz"
    sha256 "9f5e494732f204fd6b409b6b133f74e7346fd55b20d47aeafe4ee1abec656131"
  end
  
  depends_on "git"
  depends_on "hub"

  def install
    bin.install "kubernetes-job-ui"
  end
end
